- backend/build.gradle
- backend/src/main/java/com/morak/back/core/util/CodeGenerator.java
- backend/src/main/java/com/morak/back/poll/application/PollService.java
- backend/src/test/java/com/morak/back/core/util/CodeGeneratorTest.java
랜덤 코드 생성 기능을 구현했습니다. 제 아이 조심히 다뤄주세요..🐥
Close #18
> feat: 랜덤 코드 생성 기능 구현

- backend/src/main/resources/application.yml
- backend/src/test/resources/application.yml
실행 전에 환경변수 세팅하는거 잊지말아주세요!!
Close #21
> chore: 환경 변수 세팅

- backend/src/main/java/com/morak/back/auth/config/AuthConfig.java
- backend/src/main/java/com/morak/back/poll/application/PollService.java
- backend/src/main/java/com/morak/back/poll/ui/PollController.java
- backend/src/main/resources/http-test.http
- backend/src/test/java/com/morak/back/poll/acceptance/PollAcceptanceTest.java
투표 기능에 OAuth 를 적용하였습니다.
앞으로 많은 이용 부탁드립니다.
close #26
> refactor: 투표 기능에 OAuth 적용

- backend/src/main/java/com/morak/back/core/exception/GlobalControllerAdvice.java
역직렬화시 에러가 발생할 때 처리하는 로직을 추가하였습니다 🐈 
Close #28
> feat: Json 역직렬화 예외 처리 추가

- backend/src/main/java/com/morak/back/auth/domain/Member.java
- backend/src/main/java/com/morak/back/auth/ui/dto/MemberResponse.java
- backend/src/main/java/com/morak/back/poll/application/PollService.java
- backend/src/main/java/com/morak/back/poll/domain/Poll.java
- backend/src/main/java/com/morak/back/poll/domain/PollItem.java
- backend/src/main/java/com/morak/back/poll/domain/PollResult.java
- backend/src/main/java/com/morak/back/poll/ui/PollController.java
- backend/src/main/java/com/morak/back/poll/ui/dto/MemberResponse.java
- backend/src/main/java/com/morak/back/poll/ui/dto/MemberResultResponse.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollItemRequest.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollItemResponse.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollItemResultResponse.java
- backend/src/main/resources/data-local.sql
- backend/src/main/resources/http-test.http
- backend/src/main/resources/schema-dev.sql
- backend/src/main/resources/schema-local.sql
- backend/src/test/java/com/morak/back/poll/acceptance/PollAcceptanceTest.java
- backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollResultRepositoryTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollTest.java
- backend/src/test/resources/data.sql
- backend/src/test/resources/schema.sql
투표 기능에 선택 이유(description) 추가했습니다. 
- 투표할 때 선택 이유를 추가할 수 있습니다. 
- 선택 항목을 조회할 때 선택 여부와 이유도 볼 수 있습니다. (이유는 간단 명료하게!!)
저희 아이 잘 부탁드립니다🐱
Close #17 #45
> feat: 투표 기능에 선택 이유(description) 추가

- backend/src/main/java/com/morak/back/auth/config/AuthConfig.java
- backend/src/main/java/com/morak/back/team/ui/TeamController.java
- backend/src/test/java/com/morak/back/team/acceptance/TeamAcceptanceTest.java
- backend/src/test/java/com/morak/back/team/application/TeamServiceTest.java
그룹의 모든 API에 ""/api" prefix 추가
close #46
> refactor: 그룹 기능 API 명세 변경

- backend/build.gradle
- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/morak/back/auth/application/OAuthService.java
- backend/src/main/resources/schema-dev.sql
- backend/src/main/resources/schema-local.sql
- backend/src/test/java/com/morak/back/ApiDocumentUtils.java
- backend/src/test/java/com/morak/back/auth/domain/MemberRepositoryTest.java
- backend/src/test/resources/schema.sql
로그인 시 중복으로 저장되는 기능 수정
Close #54
> fix: oauth 로그인 시 회원이 중복 저장되는 버그 수정

- backend/src/main/java/com/morak/back/auth/ui/OAuthController.java
- backend/src/test/java/com/morak/back/auth/acceptance/OAuthAcceptanceTest.java
간단히 로그인 url에 `/api/`을 붙였습니다. 
피드백 마니마니 해주세요~~
Close #30
> refactor: 로그인 API url 변경

- backend/src/test/java/com/morak/back/auth/ui/OAuthControllerTest.java
oauth 테스트에서 실패하는 부분을 수정한다.
Close #85
> fix: 테스트 실패하는 부분 수정

- backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
- backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
- backend/src/main/java/com/morak/back/appointment/domain/AppointmentStatus.java
- backend/src/main/java/com/morak/back/appointment/domain/AvailableTime.java
- backend/src/main/java/com/morak/back/appointment/domain/AvailableTimeRepository.java
- backend/src/main/resources/application.yml
- backend/src/main/resources/schema-dev.sql
- backend/src/main/resources/schema-local.sql
- backend/src/test/java/com/morak/back/poll/domain/PollRepositoryTest.java
- backend/src/test/resources/schema.sql
약속 잡기 도메인을 구현하였습니다.
Close #101
> feat: 약속 잡기 도메인 구현

- backend/src/test/java/com/morak/back/SimpleRestAssured.java
- backend/src/test/java/com/morak/back/auth/acceptance/OAuthAcceptanceTest.java
- backend/src/test/java/com/morak/back/auth/application/JwtTokenProviderTest.java
- backend/src/test/java/com/morak/back/auth/application/OAuthServiceTest.java
- backend/src/test/java/com/morak/back/auth/domain/MemberRepositoryTest.java
- backend/src/test/java/com/morak/back/core/util/CodeGeneratorTest.java
- backend/src/test/java/com/morak/back/poll/acceptance/PollAcceptanceTest.java
- backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
- backend/src/test/java/com/morak/back/team/acceptance/TeamAcceptanceTest.java
- backend/src/test/java/com/morak/back/team/application/TeamServiceTest.java
- backend/src/test/resources/application.yml
인수 테스트를 가독성있게 수정하였습니다.
Close #100 #107
> refactor: 인수 테스트를 리팩토링한다.

- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
- backend/src/main/java/com/morak/back/appointment/domain/AppointmentStatus.java
- backend/src/main/java/com/morak/back/appointment/ui/AppointmentController.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentCreateRequest.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentResponse.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AvailableTimeRequest.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/RecommendationResponse.java
- backend/src/test/java/com/morak/back/appointment/domain/AppointmentStatusTest.java
- backend/src/test/java/com/morak/back/appointment/domain/AppointmentTest.java
- backend/src/test/java/com/morak/back/appointment/ui/AppointmentControllerTest.java
약속잡기 컨트롤러 테스트를 추가하고, RestDocs 문서를 작성했어요. 
🟡 나중에 해야하는 부분은 todo로 명시해놨어요. 
Close #112
> feat: 약속잡기 컨트롤러 테스트 및 RestDocs 문서 작성

- backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
- backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
- backend/src/main/java/com/morak/back/appointment/domain/AvailableTime.java
- backend/src/main/java/com/morak/back/appointment/domain/AvailableTimeRepository.java
- backend/src/main/java/com/morak/back/appointment/domain/DatePeriod.java
- backend/src/main/java/com/morak/back/appointment/domain/DateTimePeriod.java
- backend/src/main/java/com/morak/back/appointment/domain/DurationMinutes.java
- backend/src/main/java/com/morak/back/appointment/domain/TimePeriod.java
- backend/src/main/java/com/morak/back/appointment/ui/AppointmentController.java
- backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
- backend/src/test/java/com/morak/back/appointment/domain/AppointmentTest.java
- backend/src/test/java/com/morak/back/appointment/domain/AvailableTimeRepositoryTest.java
- backend/src/test/java/com/morak/back/appointment/domain/DatePeriodTest.java
- backend/src/test/java/com/morak/back/appointment/domain/DateTimePeriodTest.java
- backend/src/test/java/com/morak/back/appointment/domain/DurationMinutesTest.java
- backend/src/test/java/com/morak/back/appointment/domain/TimePeriodTest.java
- backend/src/test/resources/data.sql
약속잡기 도메인(Appointment, AvailableTime)에 임베디드를 적용하고, 이에 관한 테스트를 추가해놓았습니다😽
Close #117
> refactor: 약속잡기 도메인에 임베디드 적용 및 테스트 추가

- backend/src/main/java/com/morak/back/poll/application/PollService.java
- backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
- backend/src/main/java/com/morak/back/poll/exception/PollNotFoundException.java
- backend/src/main/java/com/morak/back/poll/ui/PollController.java
- backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollRepositoryTest.java
- backend/src/test/java/com/morak/back/poll/ui/PollControllerTest.java
- backend/src/test/resources/data.sql
> refactor(poll): path에 투표 id 대신 code 사용

- backend/src/main/java/com/morak/back/core/domain/Code.java
- backend/src/main/java/com/morak/back/poll/application/PollService.java
- backend/src/main/java/com/morak/back/poll/domain/Poll.java
- backend/src/main/java/com/morak/back/poll/domain/PollItem.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollCreateRequest.java
- backend/src/main/java/com/morak/back/team/application/TeamService.java
- backend/src/main/java/com/morak/back/team/domain/Team.java
- backend/src/main/java/com/morak/back/team/domain/TeamInvitation.java
- backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollRepositoryTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollTest.java
- backend/src/test/java/com/morak/back/team/application/TeamServiceTest.java
- backend/src/test/java/com/morak/back/team/domain/TeamInvitationTest.java
- backend/src/test/java/com/morak/back/team/domain/TeamRepositoryTest.java
> refactor: poll 도메인 리팩토링을 보완한다.

- backend/src/main/java/com/morak/back/team/ui/dto/TeamResponse.java
- backend/src/test/java/com/morak/back/team/acceptance/TeamAcceptanceTest.java
- backend/src/test/java/com/morak/back/team/ui/TeamControllerTest.java
> refactor: TeamResponse 를 수정한다.

- frontend/src/App.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateForm/AppointmentCreateForm.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormButtonGroup/AppointmentCreateFormButtonGroup.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormDescriptionInput/AppointmentCreateFormDescriptionInput.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormDurationInput/AppointmentCreateFormDurationInput.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormTimeLimitInput/AppointmentCreateFormTimeLimitInput.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormTitleInput/AppointmentCreateFormTitleInput.tsx
- frontend/src/components/GroupInit/GroupCreateForm/GroupCreateForm.tsx
- frontend/src/components/Main/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
- frontend/src/components/PollMain/PollMainDetail/PollMainDetail.tsx
- frontend/src/components/PollProgress/PollProgressDetail/PollProgressDetail.tsx
- frontend/src/components/PollProgress/PollProgressSubmitButton/PollProgressSubmitButton.tsx
- frontend/src/components/PollResult/PollResultDetail/PollResultDetail.tsx
- frontend/src/components/PollResult/PollResultStatus/PollResultStatus.tsx
- frontend/src/components/common/Button/Button.tsx
- frontend/src/components/common/Select/Select.stories.tsx
- frontend/src/components/common/Select/Select.tsx
- frontend/src/components/common/TextField/TextField.tsx
- frontend/src/hooks/useInput.ts
- frontend/src/hooks/useInputs.ts
- frontend/src/pages/AppointmentCreatePage/AppointmentCreatePage.tsx
- frontend/src/pages/AppointmentMainPage/AppointmentMainPage.tsx
- frontend/src/pages/MainPage/MainPage.tsx
- frontend/src/types/appointment.ts
- frontend/src/utils/number.ts
- frontend/tsconfig.json
- 약속 생성 페이지 UI를 구현하였습니다.
- 달력은 위니가 진행을 하고 있어, 이후에 달력 컴포넌트를 삽입하면서 API 연결까지 진행할 예정입니다.
- 위니가 병가인 관계로, review 없이 merge 할 예정입니다. 코드에 대한 리뷰는 이후, 리팩토링 과정때 하겠습니다
Close #121
> feat: 약속 생성 페이지 UI를 구현한다.

- frontend/package-lock.json
- frontend/package.json
- frontend/webpack.common.js
- frontend/webpack.dev.js
- frontend/webpack.prod.js
- 개발/배포 환경에 따라 webpack 파일을 따로 생성해주었습니다.
Close #126
> chore: webpack 개발/배포 환경 분리

- frontend/src/api/appointment.ts
- frontend/src/components/AppointmentCreate/AppointmentCreateForm/AppointmentCreateForm.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormDescriptionInput/AppointmentCreateFormDescriptionInput.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormTitleInput/AppointmentCreateFormTitleInput.tsx
- frontend/src/components/common/Calendar/Calendar.tsx
- frontend/src/pages/AppointmentCreatePage/AppointmentCreatePage.tsx
- frontend/src/types/appointment.ts
생성 페이지에 달력을 추가하고 API를 연동한다.
Close #148
> feat: 생성 페이지에 달력을 추가하고 API를 연동한다.

- backend/src/main/resources/logback-spring.xml
🟣 30일 지나면 로깅된 tar 파일을 삭제하도록 설정했습니다. 
Close #176
> refactor: 로깅 롤링 전략 변경

- frontend/src/App.tsx
- frontend/src/api/appointment.ts
- frontend/src/components/AppointmentCreate/AppointmentCreateForm/AppointmentCreateForm.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormDurationInput/AppointmentCreateFormDurationInput.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormTimeLimitInput/AppointmentCreateFormTimeLimitInput.tsx
- frontend/src/components/AppointmentProgress/AppointmentProgressButtonGroup/AppointmentProgressButtonGroup.tsx
- frontend/src/components/AppointmentProgress/AppointmentProgressDetail/AppointmentProgressDetail.tsx
- frontend/src/components/AppointmentProgress/AppointmentProgressHeader/AppointmentProgressHeader.tsx
- frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
- frontend/src/components/AppointmentResult/AppointmentResultButtonGroup.tsx
- frontend/src/components/AppointmentResult/AppointmentResultContainer/AppointmentResultContainer.tsx
- frontend/src/components/AppointmentResult/AppointmentResultRanking.tsx
- frontend/src/components/Main/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/common/Calendar/Calendar.tsx
- frontend/src/pages/AppointmentProgressPage/AppointmentProgressPage.tsx
- frontend/src/pages/LandingPage/LandingPage.tsx
- frontend/src/types/appointment.ts
- frontend/src/utils/fetcher.ts
진행 페이지에 달력을 추가하고 API를 연동하였습니다.
그외에 QA를 진행하고 발견된 버그들을 수정하였습니다.
Close #149
> feat: 약속잡기 진행 페이지에 달력을 추가하고 API를 연동한다.

- backend/src/docs/asciidoc/index.adoc
rest docs에 api 별 에러 응답 코드를 추가한다.
Close #158
> docs: api별 에러 응답 코드 추가

- backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
- backend/src/main/java/com/morak/back/appointment/domain/Appointment.java
- backend/src/main/java/com/morak/back/appointment/domain/TimePeriod.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AvailableTimeRequest.java
- backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
- backend/src/test/java/com/morak/back/appointment/domain/AppointmentTest.java
검증 로직 등을 수정하였습니다.
Close #164 #170 #181
> fix: QA 과정에서 나타난 서버 오류 수정

- backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
서비스 테스트에서 약속잡기 생성 부분이 깨져서 급하게 now()로 변경했습니다.
Close #195
> fix: 약속잡기 생성 테스트 수정

- frontend/src/api/appointment.ts
- frontend/src/components/AppointmentMain/AppointmentMainButtonGroup/AppointmentMainButtonGroup.tsx
- frontend/src/components/AppointmentMain/AppointmentMainContainer/AppointmentMainContainer.tsx
- frontend/src/components/AppointmentMain/AppointmentMainDetail/AppointmentMainDetail.tsx
- frontend/src/components/AppointmentMain/AppointmentMainHeader/AppointmentMainHeader.tsx
- frontend/src/components/AppointmentMain/AppointmentMainProgress/AppointmentMainProgress.tsx
- frontend/src/components/AppointmentMain/AppointmentMainStatus/AppointmentMainStatus.tsx
- frontend/src/components/Main/MainFeatureMenuContainer/MainFeatureMenuContainer.tsx
- frontend/src/components/PollMain/PollMainContainer/PollMainContainer.tsx
- frontend/src/components/PollMain/PollMainHeader/PollMainHeader.tsx
- frontend/src/pages/AppointmentMainPage/AppointmentMainPage.tsx
- frontend/src/types/appointment.ts
- 약속잡기 메인페이지 UI를 구현한다.
- 약속잡기 메인페이지 도메인 로직을 구현한다.
- 현재 투표하기 메인페이지와 같은 모양으로 통일했습니다. (나중 크기 등 스타일은 한번에 바꿔야할 것 같아요!) 
- 투표하기 메인페이지에도 title(투표하기 목록)이 있으면 좋을 것 같아서, 추가해주었습니다. 
- description은 한줄이 넘어가면 말줄임이 되도록 구현했습니다. (...) 
리뷰 잘 부탁드립니다 🐝👋
Close #221
> feat: 약속잡기 메인페이지를 구현한다 

- backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentCreateRequest.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AvailableTimeRequest.java
- backend/src/main/java/com/morak/back/auth/ui/dto/SigninResponse.java
- backend/src/main/java/com/morak/back/core/ui/dto/ExceptionResponse.java
- backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
- backend/src/main/java/com/morak/back/poll/ui/dto/MemberResultResponse.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollCreateRequest.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollItemResponse.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollResponse.java
- backend/src/main/java/com/morak/back/team/domain/TeamInvitationRepository.java
- backend/src/main/java/com/morak/back/team/domain/TeamRepository.java
- backend/src/main/java/com/morak/back/team/ui/dto/InvitationJoinedResponse.java
- backend/src/main/java/com/morak/back/team/ui/dto/TeamCreateRequest.java
- backend/src/main/java/com/morak/back/team/ui/dto/TeamResponse.java
테스트가 깨지는 부분이 있는데 #230 번에서 수정했습니다.
Close #236
> refactor: Build Tool을 Gradle에서 Intellij 로 변경한다.

- backend/src/main/java/com/morak/back/auth/application/dto/OAuthAccessTokenResponse.java
- backend/src/main/java/com/morak/back/auth/domain/Member.java
- backend/src/main/java/com/morak/back/core/exception/CustomErrorCode.java
- backend/src/main/java/com/morak/back/core/ui/GlobalControllerAdvice.java
- backend/src/main/java/com/morak/back/poll/application/PollService.java
- backend/src/main/java/com/morak/back/poll/domain/Poll.java
- backend/src/main/java/com/morak/back/poll/ui/PollController.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollCreateRequest.java
- backend/src/main/java/com/morak/back/team/application/TeamService.java
- backend/src/main/java/com/morak/back/team/domain/TeamInvitation.java
- backend/src/test/java/com/morak/back/auth/application/JwtTokenProviderTest.java
- backend/src/test/java/com/morak/back/auth/application/OAuthServiceTest.java
- backend/src/test/java/com/morak/back/auth/domain/MemberRepositoryTest.java
- backend/src/test/java/com/morak/back/core/domain/CodeTest.java
- backend/src/test/java/com/morak/back/poll/acceptance/PollAcceptanceTest.java
- backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollItemRepositoryTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollRepositoryTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollStatusTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollTest.java
- backend/src/test/java/com/morak/back/team/acceptance/TeamAcceptanceTest.java
- backend/src/test/java/com/morak/back/team/application/TeamServiceTest.java
- backend/src/test/java/com/morak/back/team/domain/TeamRepositoryTest.java
auth, team, poll 도메인에 대해서 수정 및 테스트 코드 추가를 해보았습니다 
clone하여서 인텔리 제이로 다운 받고, 코드 리뷰해주시는 것이 좋을 것 같아요 ~
Close #214 #216 #217
> refactor: auth, team poll 테스트 수정 및 로직 수정

- frontend/src/components/PollCreate/PollCreateCloseTimeInput/PollCreateCloseTimeInput.tsx
- frontend/src/components/PollCreate/PollCreateForm/PollCreateForm.tsx
- frontend/src/components/PollCreate/PollCreateFormTitleInput/PollCreateFormTitleInput.tsx
- frontend/src/components/PollMain/PollMainContainer/PollMainContainer.tsx
- frontend/src/components/PollMain/PollMainDetail/PollMainDetail.tsx
- frontend/src/components/PollResult/PollResultContainer/PollResultContainer.tsx
- frontend/src/components/PollResult/PollResultDetail/PollResultDetail.tsx
> feat: 투표 마감시간 기능 구현

- frontend/src/components/PollProgress/PollProgressForm/PollProgressForm.tsx
- frontend/src/components/PollProgress/PollProgressItemGroup/PollProgressItemGroup.tsx
- frontend/src/types/poll.ts
- 투표 선택항목의 api 변경에 따라 관련된 인터페이스를 수정하였습니다.
Close #248
> refactor: 투표 선택항목의 api 변경에 따라 인터페이스 수정

- frontend/src/components/AppointmentResult/AppointmentResultHeader/AppointmentResultHeader.tsx
- frontend/src/components/AppointmentResult/AppointmentResultRanking/AppointmentResultRanking.tsx
- frontend/src/pages/AppointmentResultPage/AppointmentResultPage.tsx
- frontend/src/utils/clipboard.ts
- 약속 잡기 결과페이지에서 진행 페이지로 갈 수 있는 링크를 클립보드에 복사하는 기능을 구현했습니다.
Close #251
> feat: 약속 잡기 결과페이지에서 진행 페이지로 갈 수 있는 링크 복사 기능 구현

- frontend/src/components/Sidebar/Sidebar.tsx
- 그룹 초대 링크 복사 오류 해결하였습니다
Close #260
> fix(group): 그룹 초대 링크 복사 오류 해결

- backend/src/main/java/com/morak/back/auth/application/OAuthService.java
- backend/src/main/java/com/morak/back/auth/ui/OAuthController.java
- backend/src/test/java/com/morak/back/TestConfig.java
- backend/src/test/java/com/morak/back/auth/acceptance/OAuthAcceptanceTest.java
- backend/src/test/java/com/morak/back/auth/application/FakeOAuthClient.java
- backend/src/test/java/com/morak/back/auth/application/JwtTokenProviderTest.java
- backend/src/test/java/com/morak/back/auth/application/OAuthServiceTest.java
- backend/src/test/java/com/morak/back/auth/domain/MemberTest.java
- backend/src/test/java/com/morak/back/auth/ui/OAuthControllerTest.java
- backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
- backend/src/test/java/com/morak/back/team/application/TeamServiceTest.java
`RecommendationCells` 에서 하나 테스트 깨지는 부분은 에덴이 수정할 예정입니다.
Close #245
> feat: 자기자신을 조회하는 API를 추가한다.

- frontend/src/components/PollResult/PollResultButtonGroup/PollResultButtonGroup.tsx
- frontend/src/components/PollResult/PollResultContainer/PollResultContainer.tsx
- frontend/src/components/PollResult/PollResultItemGroup/PollResultItemGroup.tsx
투표를 진행하지 않으면, 결과페이지에서 정상적으로 투표하기 버튼이 생성되도록 하였습니다.
Close #263
> fix(poll): 투표를 진행하지 않아도, 결과페이지에서 재투표하기 버튼 출력되는 문제 해결

- frontend/src/components/PollResult/PollResultContainer/PollResultContainer.tsx
- frontend/src/components/PollResult/PollResultShareLink/PollResultShareLink.tsx
- 투표 결과 페이지에 진행페이지로 갈 수 있는 링크 수정하였습니다
Close #262
> refactor(poll): 투표 결과 페이지에 진행페이지로 갈 수 있는 링크 수정

- frontend/src/components/PollMain/PollMainContainer/PollMainContainer.tsx
- frontend/src/components/PollMain/PollMainProgress/PollMainProgress.tsx
- frontend/src/components/PollResult/PollResultContainer/PollResultContainer.tsx
- frontend/src/components/PollResult/PollResultProgress/PollResultProgress.tsx
- frontend/src/types/poll.ts
- 익명 투표에서 투표자수가 제대로 뜨지 않는 에러를 수정했습니다. 
- 바뀐 api 명세에 맞춰, progress bar에서 투표자수를 보여주는 방식을 변경했습니다. (투표 메인페이지, 투표 결과페이지) 
Close #277
> fix(poll): 익명 투표에서 투표자수가 제대로 뜨지 않는 에러 수정 

- backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
- backend/src/main/java/com/morak/back/poll/application/PollService.java
- backend/src/main/java/com/morak/back/poll/domain/Poll.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollResponse.java
- backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
- backend/src/test/java/com/morak/back/poll/acceptance/PollAcceptanceTest.java
- backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollRepositoryTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollTest.java
- backend/src/test/java/com/morak/back/poll/ui/PollControllerTest.java
- backend/src/test/java/com/morak/back/team/acceptance/TeamAcceptanceTest.java
- backend/src/test/resources/data.sql
- frontend/src/components/PollMain/PollMainContainer/PollMainContainer.tsx
- frontend/src/components/PollMain/PollMainProgress/PollMainProgress.tsx
- frontend/src/components/PollResult/PollResultContainer/PollResultContainer.tsx
- frontend/src/components/PollResult/PollResultProgress/PollResultProgress.tsx
- frontend/src/types/poll.ts
> fix: 익명 투표 카운트바 로직 수정

- frontend/src/components/SidebarInvitationMenu/SidebarInvitationMenu.tsx
merge를 하면서 초대링크 복사가 안되어서 살펴보니, 
conflict 해결하면서 코드가 망가졌네요 😅 다행히 앨버가 이전에 해결해놓은 코드가 있어서 금방 해결했습니다! 
이미 merge가 된적이 있던 코드이고, 급한 사항이기 때문에 바로 merge 하겠습니다. 
(실수하지 않고 conflict 해결 잘하겠습니다 🥲) 
Close #285
> fix: 초대링크 복사 안되는 버그 해결

- frontend/src/components/PollProgress/PollProgressForm/PollProgressForm.tsx
- frontend/src/components/PollProgress/PollProgressItemGroup/PollProgressItemGroup.tsx
- 재투표시 이전 기록 보여주도록 구현하였습니다
Close #250
> feat(poll): 재투표시 이전 기록 보여주도록 기능 구현

- frontend/src/components/Invitation/InvitationContainer/InvitationContainer.tsx
- 회원가입 안되있는 상황에서, 초대장 페이지에 접속하면 로그인하라고 보내주도록 하였습니다.
Close #293
> fix: 회원가입 안되있는 상황에서, 초대장 페이지에 접속하면 무한로딩이 되는 문제 해결

- frontend/src/components/Landing/LandingMainSection/LandingMainSection.tsx
> fix: 로그인 후 localhost로 이동되는 문제 해결

- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentAllResponse.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentResponse.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollCreateRequest.java
- backend/src/main/java/com/morak/back/poll/ui/dto/PollResponse.java
- backend/src/test/java/com/morak/back/appointment/ui/AppointmentControllerTest.java
- backend/src/test/java/com/morak/back/poll/acceptance/PollAcceptanceTest.java
약속잡기 목록 조회, 단건 조회 시에 closedAt 항목을 추가하였습니다.
Close #282
> feat(appointment): 약속잡기 목록, 단건 조회 시 closedAt 항목 추가

- backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentResponse.java
- backend/src/test/java/com/morak/back/appointment/ui/AppointmentControllerTest.java
단건 조회 시 호스트 확인 항목을 응답에 추가하였습니다.
Close #306
> feat(appointment): 단건 조회 시 호스트 확인 항목 추가

- backend/src/main/resources/schema-dev.sql
- backend/src/main/resources/schema-local.sql
- backend/src/test/java/com/morak/back/appointment/acceptance/AppointmentAcceptanceTest.java
- backend/src/test/resources/schema.sql
약속잡기 삭제 시 cascade 제약조건을 설정하였습니다.
Close #308
> refactor(appointment): 약속잡기 삭제 시 cascade 제약조건 설정

- frontend/src/components/AppointmentCreate/AppointmentCreateForm/AppointmentCreateForm.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormCloseTimeInput/AppointmentCreateFormCloseTimeInput.tsx
- frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
- frontend/src/pages/AppointmentProgressPage/AppointmentProgressPage.tsx
> fix(appointment): 약속잡기에서 12:00AM로 인해 생기는 문제 해결

- frontend/src/components/PollCreate/PollCreateForm/PollCreateForm.tsx
- 투표 생성시 마감시간이 현재보다 미래가 아니면 에러메시지를 출력해주도록 구현하였습니다.
Close #300
> feat(poll): 투표 생성시 마감시간에 대한 에러 핸들링

- frontend/src/api/appointment.ts
- frontend/src/components/AppointmentResult/AppointmentResultButtonGroup/AppointmentResultButtonGroup.tsx
- frontend/src/components/AppointmentResult/AppointmentResultHeader/AppointmentResultHeader.tsx
- frontend/src/components/AppointmentResult/AppointmentResultStatus/AppointmentResultStatus.tsx
- frontend/src/pages/AppointmentProgressPage/AppointmentProgressPage.tsx
- frontend/src/pages/AppointmentResultPage/AppointmentResultPage.tsx
- frontend/src/types/appointment.ts
- 약속 잡기가 이미 종료된 경우 링크로 들어가서 확인 버튼 누르면 다른 페이지로 넘어가지도록 구현했습니다.
- 마감된 약속잡기일시, 가능시간 수정 버튼이 보이지 않도록 수정했습니다.
- 약속잡기 마감을 누르면 약속잡기를 마감하시겠습니까?라는 메시지로 수정하였습니다.
- 본인이 만든 약속잡기가 아닐때는 마감,삭제 버튼이 보이지 않도록 수정했습니다.
Close #305
> feat(appointment): 약속 잡기 결과 페이지 에러 핸들링

- frontend/src/components/SidebarMenuModals/SidebarMenuModals.tsx
모달창을 닫은 후, 다시 들어갔을 때 input창이 지워져있도록 수정했다.
Close #316
> fix(group): 그룹 생성, 참가 모달창 내부 input의 value를 비워주도록 수정

- frontend/src/components/PollProgress/PollProgressForm/PollProgressForm.tsx
- submit 핸들러 함수에서, 선택항목이 비어있으면 return을 해주었습니다.
Close #320
> fix(poll): 투표 선택항목을 선택하지 않고 투표를 했을 때 문제 해결

- frontend/src/components/AppointmentResult/AppointmentResultHeader/AppointmentResultHeader.tsx
- frontend/src/components/PollResult/PollResultContainer/PollResultContainer.tsx
- frontend/src/components/PollResult/PollResultShareLink/PollResultShareLink.tsx
- frontend/src/pages/AppointmentResultPage/AppointmentResultPage.tsx
- 투표, 약속잡기 공유 링크 세분화하였습니다
Close #323
> feat(poll, appointment): 투표, 약속잡기 공유 링크 세분화 

- frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
- 그룹 프로필 배경 색상을 파스텔톤으로 랜덤으로 나오게 구현했다.
- 그룹의 첫글자가 프로필에 표시된다.
Close #317
> feat(group): 랜덤 그룹 프로필 구현

- frontend/src/components/SidebarMenuModals/SidebarMenuModals.tsx
- alert를 띄워주고, 값을 reset해주었습니다.
Close #326
> fix(group): 이미 참여하고 있는 그룹을 코드로 참가하려고 했을 때 에러 핸들링

- frontend/src/App.tsx
- frontend/src/pages/AppointmentMainPage/AppointmentMainPage.tsx
- frontend/src/pages/MainPage/MainPage.tsx
- frontend/src/pages/PollMainPage/PollMainPage.tsx
- frontend/src/routes/MenuRoute.tsx
링크로 접속시, 사이드바 메뉴가 제대로 선택되지 않는 버그를 수정했습니다.
menu를 세팅하는 route인 MenuRoute를 만들어줘서 해결할 수 있었습니다. (PrivateRoute와 같은 원리!) 
Close #315
> fix: 링크로 접속시, 사이드바 메뉴가 제대로 선택되지 않는 버그 수정

- frontend/src/components/AppointmentCreate/AppointmentCreateForm/AppointmentCreateForm.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormButtonGroup/AppointmentCreateFormButtonGroup.tsx
- 약속잡기 생성에서 “취소“버튼을 누르면 목록으로 돌아가지 않는 문제를 해결하였습니다.
Close #328
> fix(appointment): 약속잡기 생성에서 “취소“버튼을 누르면 목록으로 돌아가지 않는 문제 해결

- backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
- backend/src/main/java/com/morak/back/appointment/domain/AvailableTimeRepository.java
- backend/src/main/resources/schema-dev.sql
- backend/src/main/resources/schema-local.sql
- backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
- backend/src/test/java/com/morak/back/appointment/domain/AvailableTimeRepositoryTest.java
- backend/src/test/resources/schema.sql
DB schema 의 cascade 옵션을 제거하고 삭제 로직을 추가하였습니다.
Close #310
> refactor(appointment): DB schema 의 cascade 옵션 제거 및 삭제 로직 추가

- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/SidebarFeatureMenu/SidebarFeatureMenu.tsx
- frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
- frontend/src/components/SidebarInvitationMenu/SidebarInvitationMenu.tsx
- frontend/src/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.tsx
- frontend/src/components/SidebarSlackMenu/SidebarSlackMenu.tsx
- frontend/src/styles/GlobalStyle.tsx
폰트를 주아체에서, 티머니로 변경하여 가독성을 높혔습니다. 
*현재 사이드바의 title이 1.7rem입니다. (2rem으로 하면 너무 크고, 딱 1.7rem이 예쁘더라구요 😅) 
이건 나중에 이야기해보고 변경하거나 해야할 것 같아요! 
Close #228
> refactor: font 변경 

- frontend/src/components/AppointmentCreate/AppointmentCreateForm/AppointmentCreateForm.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateFormCloseTimeInput/AppointmentCreateFormCloseTimeInput.tsx
- 약속잡기 생성에 대한 에러 핸들링 추가하였습니다.
대응 error 코드: 3103,3117,3102,3107
Close #333
> feat(appointment): 약속잡기 생성에 대한 에러 핸들링 추가

- backend/src/main/java/com/morak/back/poll/application/PollService.java
> fix(core): 슬랙 메세지 반대로 출력되던 버그 수정

- backend/src/docs/asciidoc/index.adoc
- backend/src/main/java/com/morak/back/team/application/TeamService.java
- backend/src/test/java/com/morak/back/team/ui/TeamControllerTest.java
rest docs에서 빠져있던 API에 대해서 추가했습니다 
Close #335
> feat(team): team에 가입하는 경우의 테스트 추가 (rest docs)

- frontend/src/api/slack.ts
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/SidebarMenuModals/SidebarMenuModals.tsx
- frontend/src/types/slack.ts
> feat: 슬랙 api를 UI와 연결한다

- frontend/src/components/SidebarGroupMenu/SidebarGroupMenu.tsx
- frontend/src/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.tsx
- frontend/src/components/SidebarMenuModals/SidebarMenuModals.tsx
여러 css 스타일을 수정했습니다. 
Close #345
> style: css 스타일 수정 

- frontend/src/components/AppointmentCreate/AppointmentCreateForm/AppointmentCreateForm.tsx
> refactor(appointment): 불필요한 초기값 제거

- frontend/src/components/AppointmentResult/AppointmentResultButtonGroup/AppointmentResultButtonGroup.tsx
-  약속잡기 결과 페이지에서 가능시간 수정 버튼내 글이 줄바꿈되는 문제 해결
Close #353
> fix(appointment): 약속잡기 결과 페이지에서 가능시간 수정 버튼내 글이 줄바꿈되는 문제 해결

- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/SidebarFeatureMenu/SidebarFeatureMenu.tsx
- frontend/src/components/SidebarGroupsModal/SidebarGroupsModal.tsx
- frontend/src/components/SidebarMenuModals/SidebarMenuModals.tsx
- frontend/src/context/MenuProvider.tsx
- frontend/src/hooks/useMenuContext.ts
- frontend/src/hooks/useMenuDispatchContext.ts
- frontend/src/routes/MenuRoute.tsx
- frontend/src/styles/GlobalStyle.tsx
- frontend/src/types/menu.ts
메뉴에 대한 context api 를 수정했습니다.
Close #365
> refactor: 메뉴에 대한 context api 수정

- frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
`AppointmentProgressTimePicker.tsx`를 리팩토링 했습니다.
아래는 주요 리팩토링 사항입니다. (이것말고도 추가적으로 있을 것이라서 변경된 코드 보고 리뷰해주시면 감사하겠습니다😀)
1. getTimes 함수 리팩토링 
함수명 변경, 변수명 변경, if문 최대한 줄이기
2. getTimeDetail 함수 생성
period, hour, minute에 대한 정보를 추출하는 로직이 중복되고 있어 하나의 함수로 추출
3. formatHM 함수 => formatHourMinutePeriod 함수로 변경
toLocalString을 활용하여 로직 단순화
4. getPlusOneDate 함수명 => getPlusOneDay로 변경
함수의 동작은 one day를 plus해주는 것이기 때문에, 동작이 더 잘 나타나도록 변경
Close #370
> refactor(appointment): 약속잡기 진행페이지내 timepicker 리팩토링

- frontend/src/components/@common/Calendar/Calendar.tsx
> refactor: calendar 컴포넌트 리팩토링

- frontend/src/components/Landing/LandingFeatureIntroductionSection/LandingFeatureIntroductionSection.tsx
- frontend/src/components/Landing/LandingMainSection/LandingMainSection.tsx
- frontend/src/components/Landing/LandingNavbar/LandingNavbar.tsx
- frontend/src/components/Landing/LandingServiceIntroductionSection/LandingServiceIntroductionSection.tsx
- frontend/src/pages/LandingPage/LandingPage.tsx
- 랜딩페이지를 리팩토링했습니다. 
- `letter-spacing: 0.1rem` 같은경우, 4 단위로 맞추면 UI가 깨지는 문제가 발생합니다. 이 부분은 어떻게 하는것이 좋을지 커멘트 부탁드려요~ 
Close #385
> refactor: 랜딩페이지 리팩토링 

- backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
- backend/src/main/java/com/morak/back/appointment/ui/AppointmentController.java
- backend/src/main/java/com/morak/back/appointment/ui/dto/AppointmentStatusResponse.java
- backend/src/test/java/com/morak/back/appointment/acceptance/AppointmentAcceptanceTest.java
- backend/src/test/java/com/morak/back/appointment/application/AppointmentServiceTest.java
- backend/src/test/java/com/morak/back/appointment/ui/AppointmentControllerTest.java
> feat(appointment): 약속잡기 진행 여부 확인 기능 추가

- frontend/src/styles/GlobalStyle.tsx
- `1920px~` : 10px
- `1919px ~ 1366px`: 8px
- `1365px`~: 7px
Close #396
> refactor: 스크린 크기에 따른 html 폰트사이즈 변경

- frontend/src/components/@common/Calendar/Calendar.tsx
- frontend/src/components/AppointmentCreate/AppointmentCreateHeader/AppointmentCreateHeader.tsx
- frontend/src/components/AppointmentProgress/AppointmentProgressTimePicker/AppointmentProgressTimePicker.tsx
- frontend/src/components/AppointmentResult/AppointmentResultButtonGroup/AppointmentResultButtonGroup.tsx
- frontend/src/pages/AppointmentResultPage/AppointmentResultPage.tsx
- frontend/src/types/appointment.ts
약속잡기 결과페이지에서 마감 버튼을 눌렀을 때 마감이 되면, 실시간으로 결과페이지가 마감된 페이지로 바뀌도록 구현했습니다.
Close #404
> feat(appointment): 약속잡기 결과페이지에서 마감 버튼을 누르면 실시간으로 마감 버튼이 보여야한다.

- frontend/src/styles/GlobalStyle.tsx
1366px 크기에 대응하는 UI가 깨지는 상황을 해결하기위해 media query를 조정해주었습니다.
> design: 반응형 폰트 사이즈 조정

- backend/src/main/java/com/morak/back/appointment/application/AppointmentService.java
- backend/src/main/java/com/morak/back/appointment/domain/AppointmentRepository.java
- backend/src/main/java/com/morak/back/appointment/domain/AvailableTimeRepository.java
- backend/src/main/java/com/morak/back/poll/application/PollService.java
- backend/src/main/java/com/morak/back/poll/domain/Poll.java
- backend/src/main/java/com/morak/back/poll/domain/PollItemRepository.java
- backend/src/main/java/com/morak/back/poll/domain/PollRepository.java
- backend/src/main/java/com/morak/back/team/application/TeamService.java
- backend/src/main/java/com/morak/back/team/domain/TeamMemberRepository.java
- backend/src/test/java/com/morak/back/appointment/domain/AppointmentRepositoryTest.java
- backend/src/test/java/com/morak/back/core/application/NotificationServiceTest.java
- backend/src/test/java/com/morak/back/poll/application/PollServiceTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollItemRepositoryTest.java
- backend/src/test/java/com/morak/back/poll/domain/PollRepositoryTest.java
- backend/src/test/java/com/morak/back/team/acceptance/TeamAcceptanceTest.java
- backend/src/test/java/com/morak/back/team/application/TeamServiceTest.java
- backend/src/test/java/com/morak/back/team/domain/TeamMemberRepositoryTest.java
- backend/src/test/resources/application.yml
> refactor: 약속잡기를 제외한 나머지 도메인의 쿼리 성능을 개선한다

- frontend/src/pages/PollCreatePage/components/PollCreateCloseTimeInput/PollCreateCloseTimeInput.tsx
- frontend/src/pages/PollCreatePage/components/PollCreateForm/PollCreateForm.tsx
투표 생성시 마감 시간 기본값을 설정해줘서 사용자가 더 편하게 투표를 만들 수 있도록 해주었습니다.
Close #391
> feat(poll): 투표 생성시 마감 시간 기본값 설정

- frontend/src/pages/AppointmentCreatePage/components/AppointmentCreateFormTimeLimitInput/AppointmentCreateFormTimeLimitInput.styles.tsx
- frontend/src/pages/AppointmentCreatePage/components/AppointmentCreateFormTimeLimitInput/AppointmentCreateFormTimeLimitInput.tsx
- frontend/src/pages/AppointmentMainPage/components/AppointmentMainContainer/AppointmentMainContainer.styles.tsx
- frontend/src/pages/AppointmentMainPage/components/AppointmentMainContainer/AppointmentMainContainer.tsx
- frontend/src/pages/AppointmentResultPage/components/AppointmentResultButtonGroup/AppointmentResultButtonGroup.styles.tsx
- frontend/src/pages/AppointmentResultPage/components/AppointmentResultButtonGroup/AppointmentResultButtonGroup.tsx
- frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.styles.tsx
- frontend/src/pages/MainPage/components/MainFeatureMenu/MainFeatureMenu.tsx
- frontend/src/pages/PollMainPage/components/PollMainContainer/PollMainContainer.styles.tsx
- frontend/src/pages/PollMainPage/components/PollMainContainer/PollMainContainer.tsx
- frontend/src/pages/RoleMainPage/RoleMainPage.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainButtonGroup/RoleMainButtonGroup.styles.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainButtonGroup/RoleMainButtonGroup.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainProgress/RoleMainProgress.styles.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainProgress/RoleMainProgress.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainResult/RoleMainResult.styles.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainResult/RoleMainResult.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainRoleEditModal/RoleMainRoleEditModal.styles.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainRoleEditModal/RoleMainRoleEditModal.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainRoleEditModalButtonGroup/RoleMainRoleEditModalButtonGroup.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainRoleEditModalInputGroup/RoleMainRoleEditModalInputGroup.styles.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainRoleEditModalInputGroup/RoleMainRoleEditModalInputGroup.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainRoles/RoleMainRoles.styles.tsx
- frontend/src/pages/RoleMainPage/components/RoleMainRoles/RoleMainRoles.tsx
역할 정하기 진행 컴포넌트 리팩토링을 페어로 진행했습니다. 
Close #458
> refactor(role): 역할 정하기 진행 컴포넌트 리팩토링

- backend/src/main/java/com/morak/back/team/application/TeamService.java
- backend/src/test/java/com/morak/back/team/application/TeamServiceTest.java
팀 조회시 팀에 속한 멤버 리스트를 반환하는데, 이 때 본인이 가장 먼저 나오도록 수정했습니다~
Close #421
> feat(team): 본인을 member list 에서 가장 앞에서 나오도록 변경

- backend/src/main/resources/schema-dev.sql
- backend/src/main/resources/schema-local.sql
> fix: role 관련 테이블 drop 쿼리 추가

- backend/src/main/java/com/morak/back/core/config/WebConfig.java
- backend/src/test/resources/application.yml
cors 를 변수로 등록하여 제한합니다.
Close #437
> chore: cors origin 설정할 수 있도록 변경

- backend/src/main/resources/application.yml
Close #465 
까라랑 엘리랑 열심히 했어요! 예쁘게 봐주세요><
- **tomcat.threads.max: 10**
- **hikari.maximum-pool-size: 5**
- 1~5로 늘리면 TPS가 늘어나지만 5 이후로부터는 큰 변화가 없다.
- **connection-timeout: 3000ms(3초)**
- 이렇게 설정해도 에러를 응답받는 요청은 없었다.
[✍️ 노션 링크](https://www.notion.so/ririhan/Hikari-CP-859ee2954dfe491a9cc3691808bb915e)
> chore: hikari cp 및 톰캣 설정

- jenkins/jenkinsfile-dev
- jenkins/jenkinsfile-prd
빌드 후 jar 파일을 전송하지 않던 문제를 해결했습니다.
> hotfix: 젠킨스 버그를 수정한다.

- frontend/src/components/Tooltip/Tooltip.styles.tsx
- frontend/src/pages/AppointmentResultPage/components/AppointmentResultButtonGroup/AppointmentResultButtonGroup.tsx
- frontend/src/pages/AppointmentResultPage/components/AppointmentResultHeader/AppointmentResultHeader.styles.tsx
- frontend/src/pages/AppointmentResultPage/components/AppointmentResultHeader/AppointmentResultHeader.tsx
- frontend/src/pages/AppointmentResultPage/components/AppointmentResultStatus/AppointmentResultStatus.tsx
- frontend/src/pages/PollResultPage/components/PollResultContainer/PollResultContainer.styles.tsx
- frontend/src/pages/PollResultPage/components/PollResultContainer/PollResultContainer.tsx
- 설명이 필요한 곳에 tooltip 추가 
Close #480
> feat: 설명이 필요한 곳에 tooltip 추가 

- frontend/src/pages/AppointmentMainPage/components/AppointmentMainContainer/AppointmentMainContainer.styles.tsx
- frontend/src/pages/AppointmentMainPage/components/AppointmentMainContainer/AppointmentMainContainer.tsx
- frontend/src/pages/PollMainPage/components/PollMainContainer/PollMainContainer.styles.tsx
- frontend/src/pages/PollMainPage/components/PollMainContainer/PollMainContainer.tsx
- 화면 사이즈에 따라 리스트가 깨지지않도록 대응해주었습니다. 
- 이후에 media query 부분은 개선해야할 것 같습니다 😅😱
Close #488
> refactor: 화면 사이즈에 따라 리스트가 깨지지않도록 대응

- jenkins/jenkinsfile-prd
> hotfix: 젠킨스 파이프라인 버그를 수정한다.

- frontend/src/layouts/NavigationLayout/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.styles.tsx
- frontend/src/pages/PollResultPage/components/PollResultButtonGroup/PollResultButtonGroup.tsx
- frontend/src/pages/PollResultPage/components/PollResultContainer/PollResultContainer.tsx
- [fix: 투표 마감 후 상태바를 실시간으로 업데이트하도록 수정](https://github.com/woowacourse-teams/2022-mo-rak/commit/7283b308d768402b47c35f7d024e4ee2f4819088)
- [fix: 사이드바의 멤버 컴포넌트 UI 수정](https://github.com/woowacourse-teams/2022-mo-rak/commit/5002d3885b9ef44ac7fcac37af174a5c9e909da8)
Close #511
> fix: 프론트엔드 QA 대응 

- frontend/src/layouts/NavigationLayout/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.styles.tsx
- frontend/src/layouts/NavigationLayout/components/SidebarMembersProfileMenu/SidebarMembersProfileMenu.tsx
> hotfix: 멤버 이름 수정 아이콘 위치 수정
